mock_db = {
    "tokyo": "Flight JL001 (Japan Time | Departs: 11:20 AM. Hotel: Atlantis The Palm | Check-in: 3:00 PM | Extras: Breakfast included.",
    "singapore": "Flight SQ031 (Singapore Airlines) | Status: Delayed 20 mins. Hotel: Marina Bay Sands | Check-in: 3:00 PM.",
    "los angeles": "Flight AA110 (American Airlines) | Status: Boarding | Departs: 7:00 AM. Hotel: The Beverly Hills Hotel | Check-in: 4:00 PM.",
    "chicago": "Flight UA553 (United Airlines) | Status: On Time | Departs: 9:15 AM. Hotel: The Palmer House Hilton | Check-in: 3:00 PM.",
    "maldives": "Flight QR672 (Qatar Airways) | Status: On Time | Departs: 8:40 PM. Hotel: Soneva Fushi Resort | Transport: Seaplane transfer confirmed.",
    "berlin": "Flight LH402 (Lufthansa) | Status: On Time | Departs: 4:30 PM. Hotel: Hotel Adlon Kempinski | Check-in: 3:00 PM.",
    "madrid": "Flight UX091 (Air Europa) | Status: On Time | Departs: 5:15 PM. Hotel: Riu Plaza España | Check-in: 3:00 PM.",
    "amsterdam": "Flight KL601 (KLM) | Status: On Time | Departs: 6:20 PM. Hotel: Pulitzer Amsterdam | Check-in: 3:00 PM.",
    "seoul": "Flight KE082 (Korean Air) | Status: Delayed 1 hour | Departs: 1:00 PM. Hotel: Lotte Hotel Seoul | Booking Ref: S30ULX.",
    "toronto": "Flight AC442 (Air Canada) | Status: On Time | Departs: 8:00 AM. Hotel: Fairmont Royal York | Check-in: 4:00 PM.",
    "cancun": "Flight B0141 (JetBlue) | Status: On Time | Departs: 10:00 AM. Hotel: Secrets The Vine | Check-in: 3:00 PM (All-Inclusive).",
    "bangkok": "Flight TG413 (Thai Airways) | StAirlines) | Status: On Time | Departs: 10:30 AM (JFK -> NRT). Hotel: Shinjuku Prince Hotel | Check-in: 3:00 PM | Booking Ref: A9B8C7.",
    "paris": "Flight AF112 (Air France) | Status: Delayed 45 mins | Departs: 11:15 PM (JFK -> CDG). Hotel: Le Meridien Etoile | Check-in: 2:00 PM | Booking Ref: P4R1S9.",
    "london": "Flight BA099 (British Airways) | Status: Cancelled | Contact airline. Hotel: The Savoy London | Status: Refund Pending.",
    "new york": "Flight DL421 (Delta) | Status: Boarding | Departs: 8:00 AM (LAX -> JFK). Hotel: The Plaza | Check-in: 4:00 PM | Room: Deluxe Suite.",
    "rome": "Flight AZ302 (ITA Airways) | Status: On Time | Departs: 5:45 PM (JFK -> FCO). Hotel: Hotel Artemide | Check-in: 2:00 PM | Transport: Airport pickup arranged.",
    "barcelona": "Flight IB440 (Iberia) | Status: On Time | Departs: 6:00 PM. Hotel: W Barcelona | Check-in: 3:00 PM | Notes: Late arrival requested.",
    "sydney": "Flight QF012 (Qantas) | Status: On Time | Departs: 10:30 PM (LAX -> SYD). Hotel: Four Seasons Sydney | Check-in: 3:00 PM (Next Day).",
    "dubai": "Flight EK202 (Emirates) | Status: On atus: On Time | Departs: 11:55 PM. Hotel: Mandarin Oriental Bangkok | Check-in: 2:00 PM.",
    "kyoto": "Train: Shinkansen Nozomi 204 | Status: On Time | Departs: 9:30 AM (Tokyo -> Kyoto). Hotel: The Ritz-Carlton Kyoto | Check-in: 3:00 PM.",
    "istanbul": "Flight TK002 (Turkish Airlines) | Status: On Time | Departs: 7:40 PM. Hotel: Çırağan Palace Kempinski | Notes: Bosphorus View Room confirmed.",
    "cape town": "Flight SA054 (South African Airways) | Status: On Time | Departs: 6:00 PM. Hotel: The Silo Hotel | Check-in: 2:00 PM.",
    "hong kong": "Flight CX881 (Cathay Pacific) | Status: On Time | Departs: 1:15 AM. Hotel: The Peninsula Hong Kong | Check-in: 2:00 PM.",
    "hawaii": "Flight HA033 (Hawaiian Airlines) | Status: On Time | Departs: 9:00 AM. Hotel: Royal Hawaiian | Check-in: 4:00 PM.",
    "las vegas": "Flight WN411 (Southwest) | Status: Delayed 30 mins. Hotel: Bellagio | Check-in: 3:00 PM.",
    "miami": "Flight NK102 (Spirit) | Status: On Time. Hotel: The Venetian | Wait, wrong city (Error in user itinerary... Hotel is Fontainebleau Miami Beach).",
    "mumbai": "Flight AI101 (Air India) | Status: On Time | Departs: 3:30 PM. Hotel: The Taj Mahal Palace | Check-in: 2:00 PM."
}
